In [0]:
import pandas as pd
import numpy as np

1. Some todos os números de 1 até 100

In [0]:
soma = 0

for n in range(1,101):
    soma += n
    
print(soma)

5050


2. Some todos os números pares de 1 até 100

In [0]:
soma = 0

for n in range(1,101):
    if n % 2 == 0:
        soma += n
    
print(soma)

2550


3. Some todos os números ímpares de 1 até 100

In [0]:
soma = 0

for n in range(1,101):
    if n % 2 != 0:
        soma += n
    
print(soma)

2500


4. Dada a lista abaixo, some todos os elementos inteiros positivos

In [0]:
lista = [-2, 2, 'celular', 10, -99, False]

In [0]:
soma = 0

for n in lista:
    if type(n) == int:
        if n > 0:
            soma += n
print(soma)

12


Exercícios Strings

1. Crie um programa em Python que receba uma string como entrada e imprima uma nova string com os caracteres na ordem inversa.

In [0]:
txt = input('Digite uma palavra: ')

print(f'{txt} - {txt[::-1]}')

Digite uma palavra:  Fernando

Fernando - odnanreF


2. Crie um programa em Python que receba uma string como entrada e imprima outra string com todas as palavras em ordem inversa.

In [0]:
txt = input('Digite uma frase: ')

print(f'{txt} - {txt[::-1]}')

Digite uma frase:  Uma frase

Uma frase - esarf amU


3. Crie um programa em Python que receba uma string como entrada e imprima outra string com todas as vogais substituídas por asteriscos (*)

In [0]:
txt = input('Digite um texto: ')
vogais = 'aeiouAEIOU'
txt_novo = ''

for letra in txt:
    if letra in vogais:
        txt_novo += '*'
    else:
        txt_novo += letra

print(txt_novo)

Digite um texto:  Fernando

F*rn*nd*


4. Crie um programa em Python que receba uma string como entrada e imprima outra string com todas as palavras que começam com letra maiúscula.

In [0]:
txt = input('Digite um texto:'))

txt_separado = txt.split()

txt_novo = ''
for palavra in txt_separado:
  if palavra[0].isupper():
    txt_novo = txt_novo + ' ' + palavra

print(txt_novo)

Digite um texto: Fernando de barros Camargo

 Fernando Camargo


5. Crie um programa em Python que receba uma string como entrada e verifique se ela é um palíndromo (ou seja, se pode ser lida da mesma forma da esquerda para a direita e da direita para a esquerda).

In [0]:
txt = input('Digite um texto:')

if txt == txt[::-1]:
  print(f'''O texto é um palíndromo.
            Texto: {txt}
            Texto invertido: {txt[::-1]}''')
else:
  print(f'''O texto não é um palíndromo
            Texto: {txt}
            Texto invertido: {txt[::-1]}''')

Digite um texto: osso

O texto é um palíndromo.
            Texto: osso
            Texto invertido: osso


6. Crie um programa em Python que receba uma string como entrada e verifique se ela é um anagrama de outra string. (ou seja, se elas possuem as mesmas letras em quantidades diferentes)

In [0]:
txt1 = input("Digite a primeira string: ")
txt2 = input("Digite a segunda string: ")

if sorted(txt1) == sorted(txt2):
  print(f'''É um anagrama.
            Texto 1: {txt1}
            Texto 2: {txt2}''')
else:
  print('Não é anagrama')

7. Crie um programa em Python que receba uma string como entrada e imprima outra string que é formada pela primeira letra de cada palavra da string original.

In [0]:
txt = input('Digite um texto:')

txt_separado = txt.split()

txt_novo = ''

for palavra in txt_separado:
    txt_novo += palavra[0]
    
print(txt)
print(txt_novo)

Digite um texto: FERNANDO DE BARROS CAMARGO

FERNANDO DE BARROS CAMARGO
FDBC


8. Crie um programa em Python que receba uma tupla de números inteiros como entrada e retorne uma nova tupla contendo apenas os números primos.

In [0]:
numeros = (2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20)

primos = []

for numero in numeros:
  if numero > 1:
    for i in range(2, numero):
      if (numero % i) == 0:
        break
    else:
      primos.append(numero)

primos = tuple(primos)
primos

Out[26]: (2, 3, 5, 7, 11, 13, 17, 19)

9. Crie um programa em Python que receba duas tuplas de números inteiros como entrada e retorne uma nova tupla contendo apenas os elementos que aparecem em ambas as tuplas.

In [0]:
tupla1 = (1, 2, 3, 4, 5)
tupla2 = (4, 5, 6, 7, 8)

tupla_iguais = []

tupla1 = set(tupla1)

for n in tupla1:
    if n in tupla2:
        tupla_iguais.append(n)
        
tupla_iguais = tuple(tupla_iguais)
tupla_iguais

Out[29]: (4, 5)

10. Crie um programa em Python que receba uma tupla de strings como entrada e retorne uma nova tupla contendo apenas as strings que começam e terminam com a mesma letra.

In [0]:
tupla = ("arara", "casa", "mala", "ovo", "paralelepípedo", "pato")
tupla_nova = []

for palavra in tupla:
    if palavra[0] == palavra[-1]:
        tupla_nova.append(palavra)
        
print(tupla_nova)

['arara', 'ovo']


# Exercícios listas

11. Crie um programa em Python que receba uma lista de números inteiros como entrada e retorne uma nova lista contendo apenas os números que aparecem um número ímpar de vezes.

In [0]:
numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 9, 8, 7, 6, 5, 4, 3, 2, 1]

unicos = set(numeros)

repetidos_impares = []

for n in unicos:
    if numeros.count(n) % 2 !=0:
        repetidos_impares.append(n)
        
print(f'Os numeros que aparecem em quantidades ímpares são: {repetidos_impares}')

Os numeros que aparecem em quantidades ímpares são: [9]


12. Crie um programa em Python que receba duas listas de números inteiros como entrada e retorne uma nova lista contendo apenas os elementos que aparecem em pelo menos uma das listas, mas não em ambas.

In [0]:
lista1 = [1, 2, 3, 4, 5, 6, 7]
lista2 = [4, 5, 6, 7, 8, 9, 10]
    
lista_nova = list(set(lista1).symmetric_difference(set(lista2)))
lista_nova

Out[33]: [1, 2, 3, 8, 9, 10]

13. Crie um programa em Python que receba duas listas de números inteiros como entrada e retorne uma nova lista contendo apenas os elementos que aparecem em ambas as listas, mas sem repetições.

In [0]:
lista1 = [1, 2, 3, 4, 5]
lista2 = [4, 5, 6, 7, 8]

lista_nova = list(set(lista1).intersection(set(lista2)))
print(lista_nova)

[4, 5]


14. Crie um programa em Python que receba uma lista de dicionários como entrada, onde cada dicionário representa um produto com nome e preço, e retorne o nome do produto mais caro.

In [0]:
produtos = [{"nome": "celular", "preco": 1500},
            {"nome": "notebook", "preco": 3500},
            {"nome": "tablet", "preco": 1200},
            {"nome": "fones de ouvido", "preco": 200},
            {"nome": "smartwatch", "preco": 800}]

In [0]:
nome = ''
preco = 0

for produto in produtos:
    if produto['preco'] > preco:
        preco = produto['preco']
        nome = produto['nome']

print(f'O produto mais caro é - {nome} - e seu preco é de: R${preco:,.2f}')

O produto mais caro é - notebook - e seu preco é de: R$3,500.00


15. Crie um programa em Python que receba um dicionário como entrada, onde as chaves representam nomes de produtos e os valores representam as quantidades disponíveis em estoque, e retorne o nome do produto com estoque mais baixo.

In [0]:
estoque = {"celular": 50, "notebook": 20, "tablet": 100, "fones de ouvido": 5, "smartwatch": 15}

In [0]:
nome = ''
qtde = 999

for produto in estoque:
    if estoque.get(produto) < qtde:
        qtde = estoque.get(produto)
        nome = produto

print(f'O produto com menos estoque é - {nome} - e seu estoque é de: {qtde}')

O produto com menos estoque é - fones de ouvido - e seu estoque é de: 5


16. Crie um programa em Python que receba uma lista de dicionários como entrada, onde cada dicionário representa um aluno com nome e notas em diferentes disciplinas, e retorne o nome do aluno com a maior média ponderada, sendo que a média ponderada deve ser calculada utilizando as notas como pesos.

In [0]:
alunos = [{"nome": "João", "notas": {"Matemática": 8.5, "Português": 9.0, "História": 7.0}},
          {"nome": "Maria", "notas": {"Matemática": 9.5, "Português": 8.5, "História": 6.0}},
          {"nome": "Pedro", "notas": {"Matemática": 7.0, "Português": 6.5, "História": 9.0}},
          {"nome": "Ana", "notas": {"Matemática": 8.0, "Português": 7.5, "História": 8.0}}]

# 2 3 2

In [0]:
nome_maior = ''
media_maior = 0

for aluno in alunos:
    nome = aluno.get('nome')
    media = ((aluno.get('notas')['Matemática']*2 + aluno.get('notas')['Português']*3 + aluno.get('notas')['História']*2) / 7)
    print(f'Aluno: {nome} - Média Ponderada: {media:.2f}')
    if media > media_maior:
        media_maior = media
        nome_maior = nome

print(f'\nO aluno com a maior média ponderada é - {nome_maior} - e sua média é: {media_maior:.2f}')

Aluno: João - Média Ponderada: 8.29
Aluno: Maria - Média Ponderada: 8.07
Aluno: Pedro - Média Ponderada: 7.36
Aluno: Ana - Média Ponderada: 7.79

O aluno com a maior média ponderada é - João - e sua média é: 8.29


17. Crie um programa em Python que receba três números como entrada e imprima "Maior" se o primeiro número for maior do que a soma dos outros dois, "Menor" se o primeiro número for menor do que a soma dos outros dois, ou "Igual" caso contrário.

In [0]:
num1 = float(input("Digite o primeiro número: "))
num2 = float(input("Digite o segundo número: "))
num3 = float(input("Digite o terceiro número: "))

if num1 > (num2+num3):
    print(f'O primeiro número - {num1} - é maior que a soma do segundo número - {num2} - e terceiro numero - {num3} - Soma: {num2+num3}')
elif num1 < (num2+num3):
    print(f'O primeiro número - {num1} - é menor que a soma do segundo número - {num2} - e terceiro numero - {num3} - Soma: {num2+num3}')
else:
    print(f'O primeiro número - {num1} - é igual a soma do segundo número - {num2} - e terceiro numero - {num3} - Soma: {num2+num3}')

Digite o primeiro número:  7

Digite o segundo número:  1

Digite o terceiro número:  1

O primeiro número - 7.0 - é maior que a soma do segundo número - 1.0 - e terceiro numero - 1.0 - Soma: 2.0


18. Crie um programa em Python que receba a idade e a altura de uma pessoa como entrada e classifique-a de acordo com as seguintes regras: se a idade for menor do que 18 anos e a altura for menor do que 1,60 m, imprimir "Adolescente Baixo"; se a idade for menor do que 18 anos e a altura for maior do que 1,60 m, imprimir "Adolescente Alto"; se a idade for maior ou igual a 18 anos e a altura for menor do que 1,60 m, imprimir "Adulto Baixo"; se a idade for maior ou igual a 18 anos e a altura for maior do que 1,60 m, imprimir "Adulto Alto".

In [0]:
idade = int(input("Digite a idade: "))
altura = float(input("Digite a altura (em metros): "))

if idade < 18 and altura < 1.60:
  print(f'Adolescente Baixo - Idade: {idade} - Altura: {altura}')
elif idade < 18 and altura >= 1.60:
  print(f'Adolescente Alto - Idade: {idade} - Altura: {altura}')
elif idade >= 18 and altura < 1.60:
  print(f'Adulto Baixo - Idade: {idade} - Altura: {altura}')
elif idade >= 18 and altura >= 1.60:
  print(f'Adulto Alto - Idade: {idade} - Altura: {altura}')

Digite a idade:  18

Digite a altura (em metros):  1.5

Adulto Baixo - Idade: 18 - Altura: 1.5


19. Crie um programa em Python que receba uma string como entrada e imprima "Palíndromo" se a string for um palíndromo (ou seja, se a string lida de trás para frente for igual à string original), ou "Não Palíndromo" caso contrário.

In [0]:
txt = input('Digite um texto:')

if txt == txt[::-1]:
  print(f'''O texto é um palíndromo.
            Texto: {txt}
            Texto invertido: {txt[::-1]}''')
else:
  print(f'''O texto não é um palíndromo
            Texto: {txt}
            Texto invertido: {txt[::-1]}''')

Digite um texto: FernandoodnanreF

O texto é um palíndromo.
            Texto: FernandoodnanreF
            Texto invertido: FernandoodnanreF


20. Crie um programa em Python que receba uma lista de números inteiros como entrada e calcule a soma dos quadrados dos números ímpares da lista.

In [0]:
lista = [1,2,3,4,5,6,7,8,9]
soma = 0

for numero in lista:
    if numero %2 != 0:
        soma += numero**2
        
print(f'A soma dos quadrdos dos números impares da lista é: {soma}')

A soma dos quadrdos dos números impares da lista é: 165


21. Crie um programa em Python que receba uma string como entrada e imprima a string sem as vogais.

In [0]:
txt = input('Digite um texto: ')
vogais = 'aeiouAEIOU'
txt_novo = ''

for letra in txt:
    if letra not in vogais:
        txt_novo += letra

print(txt_novo)        

Digite um texto:  Fernando

Frnnd


22. Crie um programa em Python que imprima a soma dos n primeiros números primos, onde n é um número fornecido pelo usuário.

In [0]:
n = int(input('Digite um número inteiro positivo: '))
soma = 0
conta = 0
num = 2
while conta < n:
    primo = True
    for i in range(2, num):
        if num % i == 0:
           primo = False
           break
    if primo:
        soma += num
        conta += 1
    num += 1
print(f'A soma dos {n} primeiros números primos é: {soma}')

Digite um número inteiro positivo:  5

A soma dos 5 primeiros números primos é: 28


23. Crie um programa em Python que receba uma lista de números e imprima a soma dos números pares e a soma dos números ímpares presentes na lista.

In [0]:
lista = [1,2,3,4]
pares = 0
impares = 0

for numero in lista:
  if numero % 2 == 0:
    pares += numero
  else:
    impares += numero
    
print(f'A soma dos números pares é: {pares}')
print(f'A soma dos números pares é: {impares}')

A soma dos números pares é: 6
A soma dos números pares é: 4


24. Crie um programa em Python que receba uma lista de strings e retorne uma lista com todas as strings que começam e terminam com a mesma letra.

In [0]:
palavras = ["amor", "futebol", "verdade", "banana", "arara", "casa", "sol"]
palavras_selecionadas = []

for palavra in palavras:
  if palavra == palavra[::-1]:
    palavras_selecionadas.append(palavra)

print(f'As palavras que começam e terminam com a mesma letra são: {palavras_selecionadas}')

As palavras que começam e terminam com a mesma letra são: ['arara']


25. Crie um programa em Python que leia um número do usuário e verifique se ele é um número perfeito. Um número perfeito é aquele que é igual à soma de seus divisores próprios (ou seja, a soma de seus fatores inteiros positivos, excluindo ele próprio).

In [0]:
numero = int(input("Digite um número: "))
soma = 0

for i in range(1, numero):
    if numero % i == 0:
        soma += i

if numero == soma:
    print(f'O numero {numero} é perfeito. A soma dos seus divisores é: {soma}')
else:
    print(f'O número - {numero} - não é perfeito. A soma dos seus divisores é: {soma}')

Digite um número:  7

O número - 7 - não é perfeito. A soma dos seus divisores é: 1


26. Crie um programa em Python que calcule a série de Fibonacci para um determinado número de termos fornecido pelo usuário. A série de Fibonacci é uma sequência em que cada número é a soma dos dois números anteriores: 0, 1, 1, 2, 3, 5, 8, 13, ...

In [0]:
termos = int(input("Digite o número de termos desejados: "))
fibonacci = []
i = 1
n1 = 0
n2 = 1
n3 = 0

while i <= termos:
  fibonacci.append(n3)
  n1 = n2
  n2 = n3
  n3 = n1 + n2
  i += 1


print(f'Os primeiros {termos} termos de fibonacci são: {fibonacci}')

Digite o número de termos desejados:  10000

Os primeiros 10000 termos de fibonacci são: [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049, 12586269025, 20365011074, 32951280099, 53316291173, 86267571272, 139583862445, 225851433717, 365435296162, 591286729879, 956722026041, 1548008755920, 2504730781961, 4052739537881, 6557470319842, 10610209857723, 17167680177565, 27777890035288, 44945570212853, 72723460248141, 117669030460994, 190392490709135, 308061521170129, 498454011879264, 806515533049393, 1304969544928657, 2111485077978050, 3416454622906707, 5527939700884757, 8944394323791464, 14472334024676221, 23416728348467685, 37889062373143906, 61305790721611591, 99194853094755497, 160500643816367088, 259695496911122585, 42019

# Exercícios - Pandas

1. Ler e exibir um arquivo CSV usando pandas

In [0]:
df = spark.read.csv('/FileStore/tables/retail-2.csv', sep=';', header = True)

In [0]:
df = df.toPandas()
df.head()

invoice_no 
 stock_code 
 description 
 quantity 
 invoice_date 
 unit_price 
 customer_id 
 region 
 
 
 
 
 0 
 536365 
 85123A 
 WHITE HANGING HEART T-LIGHT HOLDER 
 6 
 01/12/2010 08:26 
 2,55 
 17850 
 United Kingdom 
 
 
 1 
 536365 
 71053 
 WHITE METAL LANTERN 
 6 
 01/12/2010 08:26 
 3,39 
 17850 
 United Kingdom 
 
 
 2 
 536365 
 84406B 
 CREAM CUPID HEARTS COAT HANGER 
 8 
 01/12/2010 08:26 
 2,75 
 17850 
 United Kingdom 
 
 
 3 
 536365 
 84029G 
 KNITTED UNION FLAG HOT WATER BOTTLE 
 6 
 01/12/2010 08:26 
 3,39 
 17850 
 United Kingdom 
 
 
 4 
 536365 
 84029E 
 RED WOOLLY HOTTIE WHITE HEART. 
 6 
 01/12/2010 08:26 
 3,39 
 17850 
 United Kingdom

2. Selecionar colunas específicas de um DataFrame usando pandas

In [0]:
df[['stock_code', 'unit_price']]

stock_code 
 unit_price 
 
 
 
 
 0 
 85123A 
 2,55 
 
 
 1 
 71053 
 3,39 
 
 
 2 
 84406B 
 2,75 
 
 
 3 
 84029G 
 3,39 
 
 
 4 
 84029E 
 3,39 
 
 
 ... 
 ... 
 ... 
 
 
 541904 
 22613 
 0,85 
 
 
 541905 
 22899 
 2,1 
 
 
 541906 
 23254 
 4,15 
 
 
 541907 
 23255 
 4,15 
 
 
 541908 
 22138 
 4,95 
 
 
 
 541909 rows × 2 columns

3. Filtrar linhas com base em uma condição usando pandas

In [0]:
df.loc[df['invoice_no'] == '536365']

invoice_no 
 stock_code 
 description 
 quantity 
 invoice_date 
 unit_price 
 customer_id 
 region 
 
 
 
 
 0 
 536365 
 85123A 
 WHITE HANGING HEART T-LIGHT HOLDER 
 6 
 01/12/2010 08:26 
 2,55 
 17850 
 United Kingdom 
 
 
 1 
 536365 
 71053 
 WHITE METAL LANTERN 
 6 
 01/12/2010 08:26 
 3,39 
 17850 
 United Kingdom 
 
 
 2 
 536365 
 84406B 
 CREAM CUPID HEARTS COAT HANGER 
 8 
 01/12/2010 08:26 
 2,75 
 17850 
 United Kingdom 
 
 
 3 
 536365 
 84029G 
 KNITTED UNION FLAG HOT WATER BOTTLE 
 6 
 01/12/2010 08:26 
 3,39 
 17850 
 United Kingdom 
 
 
 4 
 536365 
 84029E 
 RED WOOLLY HOTTIE WHITE HEART. 
 6 
 01/12/2010 08:26 
 3,39 
 17850 
 United Kingdom 
 
 
 5 
 536365 
 22752 
 SET 7 BABUSHKA NESTING BOXES 
 2 
 01/12/2010 08:26 
 7,65 
 17850 
 United Kingdom 
 
 
 6 
 536365 
 21730 
 GLASS STAR FROSTED T-LIGHT HOLDER 
 6 
 01/12/2010 08:26 
 4,25 
 17850 
 United Kingdom

In [0]:
df.loc[df['customer_id'] == '17850']

invoice_no 
 stock_code 
 description 
 quantity 
 invoice_date 
 unit_price 
 customer_id 
 region 
 
 
 
 
 0 
 536365 
 85123A 
 WHITE HANGING HEART T-LIGHT HOLDER 
 6 
 01/12/2010 08:26 
 2,55 
 17850 
 United Kingdom 
 
 
 1 
 536365 
 71053 
 WHITE METAL LANTERN 
 6 
 01/12/2010 08:26 
 3,39 
 17850 
 United Kingdom 
 
 
 2 
 536365 
 84406B 
 CREAM CUPID HEARTS COAT HANGER 
 8 
 01/12/2010 08:26 
 2,75 
 17850 
 United Kingdom 
 
 
 3 
 536365 
 84029G 
 KNITTED UNION FLAG HOT WATER BOTTLE 
 6 
 01/12/2010 08:26 
 3,39 
 17850 
 United Kingdom 
 
 
 4 
 536365 
 84029E 
 RED WOOLLY HOTTIE WHITE HEART. 
 6 
 01/12/2010 08:26 
 3,39 
 17850 
 United Kingdom 
 
 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 
 
 86898 
 C543611 
 82483 
 WOOD 2 DRAWER CABINET WHITE FINISH 
 -1 
 10/02/2011 14:38 
 4,95 
 17850 
 United Kingdom 
 
 
 86899 
 C543611 
 21874 
 GIN AND TONIC MUG 
 -1 
 10/02/2011 14:38 
 1,06 
 17850 
 United Kingdom 
 
 
 86900 
 C543611 
 71477 
 COLOUR GLASS. STAR T-LIGHT HOLDER 
 -2 
 10/02/2011 14:38 
 2,75 
 17850 
 United Kingdom 
 
 
 86901 
 C543611 
 82483 
 WOOD 2 DRAWER CABINET WHITE FINISH 
 -1 
 10/02/2011 14:38 
 4,95 
 17850 
 United Kingdom 
 
 
 86902 
 C543611 
 21169 
 YOU'RE CONFUSING ME METAL SIGN 
 -2 
 10/02/2011 14:38 
 1,45 
 17850 
 United Kingdom 
 
 
 
 312 rows × 8 columns

4. Agrupar dados com base em uma coluna usando pandas

In [0]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype 
---  ------        --------------   ----- 
 0   invoice_no    541909 non-null  object
 1   stock_code    541909 non-null  object
 2   description   540455 non-null  object
 3   quantity      541909 non-null  object
 4   invoice_date  541909 non-null  object
 5   unit_price    541909 non-null  object
 6   customer_id   406829 non-null  object
 7   region        541909 non-null  object
dtypes: object(8)
memory usage: 33.1+ MB


In [0]:
df.groupby('invoice_no').agg(n=('quantity', 'count')).sort_values(by='n', ascending= False).reset_index()

invoice_no 
 n 
 
 
 
 
 0 
 573585 
 1114 
 
 
 1 
 581219 
 749 
 
 
 2 
 581492 
 731 
 
 
 3 
 580729 
 721 
 
 
 4 
 558475 
 705 
 
 
 ... 
 ... 
 ... 
 
 
 25895 
 557509 
 1 
 
 
 25896 
 540264 
 1 
 
 
 25897 
 540272 
 1 
 
 
 25898 
 557501 
 1 
 
 
 25899 
 569420 
 1 
 
 
 
 25900 rows × 2 columns

5. Usar a função max em alguma coluna do DataFrame

In [0]:
df['unit_price'].max()

Out[31]: '99,96'

# Exercícios - Numpy

1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
arr = np.random.randint(1,50,10)

media_arr = arr.mean()

desvio = np.std(arr)

print(f'Array: {arr}')
print(f'A média é: {media_arr}')
print(f'O desvio padrão é: {desvio}')

Array: [32 24 20 27 38 37 38  5 13 25]
A média é: 25.9
O desvio padrão é: 10.47329938462565


2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
import numpy as np

arr = np.random.rand(10)


# professor
print(np.sqrt(arr[arr <= 0.5]))

# meu :S
for i,n in enumerate(arr):
  if n <= 0.5:
    print(f'\nO número - {n} - de posição {i} é menor que 0.5. Sua raiz quadrada é: {n**0.5}')
    
print(f'\n{arr}')

[0.45341287 0.51103518 0.55177492 0.40720075 0.55107675 0.55714534]

O número - 0.2055832312833712 - de posição 1 é menor que 0.5. Sua raiz quadrada é: 0.4534128706635611

O número - 0.2611569518764524 - de posição 2 é menor que 0.5. Sua raiz quadrada é: 0.5110351767505368

O número - 0.30445556543286767 - de posição 3 é menor que 0.5. Sua raiz quadrada é: 0.5517749228017413

O número - 0.16581245256572652 - de posição 5 é menor que 0.5. Sua raiz quadrada é: 0.40720075216743706

O número - 0.3036855827102557 - de posição 6 é menor que 0.5. Sua raiz quadrada é: 0.5510767484754331

O número - 0.3104109302597068 - de posição 7 é menor que 0.5. Sua raiz quadrada é: 0.5571453403374265

[0.81002355 0.20558323 0.26115695 0.30445557 0.50474783 0.16581245
 0.30368558 0.31041093 0.99828007 0.53950073]


3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
arr = np.random.rand(3, 3, 3)

print(f'{arr}\n')


print('RESPOSTA PROFESSOR\n')

#professor
print(np.amax(arr, axis = 1))

print('\nMINHA RESPOSTA\n')

#meu
print(f'\n{arr.max(axis=1)}')


[[[0.17325859 0.63254455 0.83414464]
  [0.69465134 0.3331395  0.04794806]
  [0.65957378 0.6449751  0.13872042]]

 [[0.30198756 0.07108404 0.4979164 ]
  [0.87372433 0.39190623 0.98085554]
  [0.83228233 0.72809644 0.32873451]]

 [[0.97511185 0.83491215 0.52609695]
  [0.2537195  0.05832129 0.90646744]
  [0.79434552 0.72014789 0.3827057 ]]]

RESPOSTA PROFESSOR

[[0.69465134 0.6449751  0.83414464]
 [0.87372433 0.72809644 0.98085554]
 [0.97511185 0.83491215 0.90646744]]

MINHA RESPOSTA


[[0.69465134 0.6449751  0.83414464]
 [0.87372433 0.72809644 0.98085554]
 [0.97511185 0.83491215 0.90646744]]


4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
arr = np.random.rand(5,5)

# professor

med = np.mean(arr, axis=1)

matriz_linha_media = arr - med[:, np.newaxis]

print(f'{arr}\n')
print(f'{med}\n')
print(f'{matriz_linha_media}\n')

# meu

for i in arr:
  media = i.mean()
  for n in i:
    print(n-media)

[[0.19401536 0.97246877 0.93601298 0.19970659 0.74455053]
 [0.05351111 0.64836326 0.17008841 0.85724772 0.02212694]
 [0.74474023 0.77864312 0.5028783  0.05622939 0.77507258]
 [0.87182174 0.06353539 0.04699784 0.13701103 0.30617908]
 [0.18813802 0.4576417  0.01843921 0.97284846 0.1505023 ]]

[0.60935085 0.35026749 0.57151272 0.28510902 0.35751394]

[[-0.41533549  0.36311793  0.32666214 -0.40964426  0.13519968]
 [-0.29675637  0.29809577 -0.18017908  0.50698023 -0.32814055]
 [ 0.1732275   0.20713039 -0.06863442 -0.51528333  0.20355985]
 [ 0.58671272 -0.22157362 -0.23811118 -0.14809798  0.02107006]
 [-0.16937592  0.10012777 -0.33907473  0.61533452 -0.20701164]]

-0.41533548672367626
0.36311792520637487
0.32666213524703114
-0.40964425780560765
0.13519968407587835
-0.29675637432451024
0.29809577098103696
-0.18017908175194536
0.5069802325870676
-0.32814054749164895
0.17322750296868006
0.20713039482639062
-0.06863442080969939
-0.5152833303027095
0.20355985331733806
0.5867127239228517
-0.221573

5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
arr = np.random.rand(4,4)

diagonal = np.diag(arr)
diagonal_inversa = np.fliplr(arr).diagonal()

media = np.mean([diagonal, diagonal_inversa])
desvio = np.std([diagonal, diagonal_inversa])

print(f'{arr}\n')

print(f'A diagonal principal é - {diagonal}.\n')
print(f'A diagonal inversa é - {diagonal_inversa}.\n')

print(f'Média diagonais: {media}\n')
print(f'Desvio padrão diagonais: {desvio}\n')

[[0.46428401 0.94972025 0.1016552  0.25606731]
 [0.99696213 0.14188635 0.14187264 0.37613523]
 [0.74405958 0.04093714 0.40016783 0.75667228]
 [0.41632872 0.87443838 0.10613746 0.42559982]]

A diagonal principal é - [0.46428401 0.14188635 0.40016783 0.42559982].

A diagonal inversa é - [0.25606731 0.14187264 0.04093714 0.41632872].

Média diagonais: 0.285892975798689

Desvio padrão diagonais: 0.1515694092997954

